hl.on("hyprland.start", function ()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("awww-daemon &")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 24")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &")
    hl.exec_cmd("clipse -listen")
    hl.exec_cmd("dunst")
end)
